cache result from eth_chainId
subquery/subql-ethereum pull request #123
Opened 2023-07-03 07:50 UTC by DeveloperInProgress

# Description
Cache chainId in `JsonBatchRpcProvider` to prevent multiple calls to `eth_chainId`

Fixes https://github.com/subquery/subql/issues/1856

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

2023-07-03 20:45 UTC, stwiname requested changes
Id rather we figure out the cause of the problem and fix that, this doesn't work if we're using websockets.

Also can you please update the changelog, from now on if PRs dont have updated changelogs then when releases are made we don't check to add it

2023-07-04 03:00 UTC, DeveloperInProgress commented
> Id rather we figure out the cause of the problem and fix that, this doesn't work if we're using websockets.
> 
> Also can you please update the changelog, from now on if PRs dont have updated changelogs then when releases are made we don't check to add it

It's seems to be in the implementation of AbstractProvider (base provider) class in ethers.js. It always calls the `getNetwork` function from `getBlock`
https://github.com/ethers-io/ethers.js/blob/3c17cf56b5164236108269ac1e36d66e2843cd1e/lib.commonjs/providers/abstract-provider.js#L745

The `getNetwork()` function always checks the stored chainId with the one from actual connected network
https://github.com/ethers-io/ethers.js/blob/3c17cf56b5164236108269ac1e36d66e2843cd1e/lib.commonjs/providers/abstract-provider.js#L559

2023-07-04 08:14 UTC, stwiname approved these changes

2023-07-04 08:36 UTC, stwiname approved these changes

2023-07-04 08:36 UTC, merged